- name: Create profiles.yml
  run: |
    mkdir -p ~/.dbt
    cat > ~/.dbt/profiles.yml <<EOF
dbt_test:
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "${GCP_PROJECT_ID}"
      dataset: "${GCP_BQ_DATASET}"
      keyfile_json: ${GCP_KEYFILE_JSON}
      threads: 1
  target: dev
EOF

    echo "profiles.yml generated:"
    cat ~/.dbt/profiles.yml

