- name: Generate profiles.yml and debug (all in one)
  env:
    DBT_PROFILES_DIR: ~/.dbt
  run: |
    mkdir -p ~/.dbt

    echo "dbt_test:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: \"${{ secrets.GCP_PROJECT }}\"
      dataset: \"dbt_prod\"
      location: \"EU\"
      keyfile_json: ${{ secrets.GCP_KEYFILE_JSON }}
      threads: 4
      timeout_seconds: 300
" > ~/.dbt/profiles.yml

    echo "------ ~/.dbt directory ------"
    ls -la ~/.dbt

    echo "------ profiles.yml content ------"
    cat ~/.dbt/profiles.yml

    echo "------ dbt debug ------"
    dbt debug --target prod
