name: dbt CI/CD (v4)

on:
  # push:
  #  branches:
  #   - main           # Déclenche le job sur push dans main
  workflow_dispatch:   # Permet de déclencher manuellement depuis l'UI Actions
  # schedule:
  #  - cron: '0 6 * * *' # (Optionnel) Déclenche chaque jour à 06:00

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ~/.dbt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dbt (BigQuery version)
        run: |
          pip install dbt-bigquery

      - name: Set up GCP credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEYFILE }}
        run: |
          echo "${GOOGLE_APPLICATION_CREDENTIALS}" > ./keyfile.json

      - name: Create profiles.yml 
        run: |
          mkdir -p ~/.dbt
          echo "dbt_test:
        target: prod
        outputs:
          prod:
            type: bigquery
            method: service-account
            project: \"${{ secrets.GCP_PROJECT }}\"
            dataset: \"${{ secrets.BQ_DATASET }}\"
            location: \"EU\"
            keyfile_json: ${{ secrets.GCP_KEYFILE_JSON }}
            threads: 4
            timeout_seconds: 300
"> ~/.dbt/profiles.yml
         
      - name: Debug dbt
        run: |
          dbt debug --target prod

      - name: Download last manifest
        uses: actions/download-artifact@v4
        with:
          name: manifest
          path: last_manifest/
        continue-on-error: true

      - name: Run dbt build on state:modified+
        run: |
          dbt deps
          dbt build --target prod --select state:modified+ --state last_manifest/

      - name: Upload manifest.json for next run
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: target/manifest.json
       
