name: dbt CI/CD

on:
  workflow_dispatch:  # Tu déclenches manuellement

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ~/.dbt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt (BigQuery)
        run: |
          pip install dbt-bigquery

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "dbt_test:
            target: prod
            outputs:
              prod:
                type: bigquery
                method: service-account
                project: \"${{ secrets.GCP_PROJECT }}\"
                dataset: \"dbt_prod\"
                location: \"EU\"
                keyfile_json: ${{ secrets.GCP_KEYFILE_JSON }}
                threads: 4
                timeout_seconds: 300" > ~/.dbt/profiles.yml

      - name: Check that profiles.yml exists
        run: |
          echo "------ DBT_PROFILES_DIR: $DBT_PROFILES_DIR ------"
          ls -la ~
          ls -la ~/.dbt
          echo "------ profiles.yml content ------"
          cat ~/.dbt/profiles.yml

      - name: Run dbt debug 
        run: |
          dbt debug --target prod

      - name: Run dbt build on state:modified+
        run: |
          dbt deps
          dbt build --target prod --select state:modified+ --state last_manifest/

